# Generated by Django 2.0.7 on 2018-11-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(max_length=10),
        ),
    ]
