# Generated by Django 2.0.7 on 2018-11-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20181120_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='mobile_number',
            field=models.IntegerField(),
        ),
    ]
