# Generated by Django 2.1.3 on 2018-11-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_concerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concerts',
            name='number_of_seats',
        ),
        migrations.AddField(
            model_name='concerts',
            name='seats_left',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='concerts',
            name='seats_total',
            field=models.IntegerField(default=0),
        ),
    ]
