# Generated by Django 2.1.3 on 2018-12-09 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_auto_20181128_2330'),
    ]

    operations = [
        migrations.CreateModel(
            name='SendMessageAgain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_received', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.MobileNumber')),
            ],
        ),
    ]
