# Generated by Django 2.1.3 on 2018-12-16 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_auto_20181210_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concerts',
            old_name='band',
            new_name='event_type',
        ),
    ]
