# Generated by Django 2.1.3 on 2018-12-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_auto_20181218_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.FloatField(),
        ),
    ]
