# Generated by Django 2.1.3 on 2018-12-09 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_sendmessageagain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessageagain',
            name='time_received',
            field=models.TimeField(),
        ),
    ]
