# Generated by Django 2.1.3 on 2018-12-09 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_auto_20181209_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendmessageagain',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
