# Generated by Django 2.1.3 on 2018-12-18 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_auto_20181216_2122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Concerts',
            new_name='Events',
        ),
    ]
