# Generated by Django 2.1.3 on 2018-12-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_auto_20181218_1255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='seats_left',
            new_name='seats_bought',
        ),
        migrations.RemoveField(
            model_name='events',
            name='seats_total',
        ),
    ]
