# Generated by Django 2.1.3 on 2018-12-18 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_auto_20181218_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedticket',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
